#!/usr/bin/env bash
# shellcheck disable=SC2086
# Information about server domains

check_domain() {
    if [ $# -lt 1 ]
    then
        echo "Less than one"
        exit 0
    fi
    SUBDOMAINS=("www"  "lb-01" "web-01" "web-02")
    if [ -z "$2" ]
    then
	for i in "${SUBDOMAINS[@]}"
    do
        url=$i.$1
        record=`dig $url | grep "$1" | tail -1 | awk '{ print $4 }'`
        ip=`dig $url | grep "$1" | tail -1 | awk '{ print $5}'`
        echo "The subdomain $i is a $record record and points to $ip"
    done
    else
        url=$2.$1
        record=`dig $url | grep "$url" | tail -1 | awk '{ print $4 }'`
        ip=`dig $url | grep "$url" | tail -1 | awk '{ print $5}'`
        echo "The subdomain $2 is a $record record and points to $ip"
    fi
}
check_domain "$@"
