#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [[ $# < 3 ]];
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
export FLAG="-o StrictHostKeyChecking=no"
priv_key_path=$4
file_path=$1
user=$3
ip=$2
scp -i $FLAG "$priv_key_path" "$file_path" "$user"@"$ip:~/"
