#!/usr/bin/env bash
# Transfers file from local machine to a remote server
if [[ $# -lt 4 ]]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

export FILE="$1"
user="$2"
ip="$3"
ssh_path="$4"

scp -o StrictHostKeyChecking=no "$FILE" "$user@$ip:~/"
