#!/usr/bin/env bash
# Bash script to Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i "15i \\\tadd_header X-SERVED-BY 36789-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart
