#!/usr/bin/env bash
# Bash script to Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install nginx
sudo service nginx start
sed -i "15i \\\tadd_header X-SERVED-BY 36789-web-01;"
sudo service nginx restart
