#!/usr/bin/env bash
# Bash script to configure HAproxy
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy
echo -e "frontend http\n\tbind :80\
    \n\tmode http\n\tdefault_backend web-backend
backend web-backend\n\tbalance roundrobin\
    \n\tserver 36789-web-01 54.172.51.196\
    \n\tserver 36789-web-02 54.89.29.168" >\
    file # /etc/haproxy/haproxy.cfg

sudo service haproxy restart
